### PR TITLE
Some typos

### PR DESCRIPTION
**Pull request by jeckodevelopment**
Fixed a few typos in the Readme file.

### CODE REVIEW

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks! Btw, an updated readme is coming, including a sample database too

**Comment by brianteeman** [comment]
So i wont bother submitting more corrections then ;)

**Comment by jeckodevelopment** [comment]
@sanderpotjer why do we need a sample database?

**Comment by sanderpotjer** [comment]
@brianteeman nope, better wait until the updated readme and submit the corrections for that one ;)

@jeckodevelopment allowing people to setup local development version of the site, and make code contributions easier

**Comment by jeckodevelopment** [comment]
ok, thank you ;)

**Pull request merged**
